### ISSUE TITLE
Help: TypeInitializationException when Run

### ISSUE THREAD

**Issue by bs135** [NonFactors/MVC5.Template#4]
Hello,

Thank you for this useful opensource.

I'm trying to learn how to use "MVC5.Template" and having a problem. I need your help.

I do step by step:
- Git Clone the project, branch master (tag v1.6.0)
- Build project: DONE
- Run "Update-Database" command on "MvcTemplate.Data": DONE
- Set "MvcTemplate.Web" as StartUp Project
- Start (F5)

And I get error below. 
Please give me some informations to solve this problem. Let me know if you need more information.

![screenshot 2016-06-07 14 45 09](https://cloud.githubusercontent.com/assets/1736277/15850042/fca640b6-2cbf-11e6-9286-8fc4af47a994.png)

```
System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception.
  Source=EntityFramework
  TypeName=System.Data.Entity.Internal.AppConfig
  StackTrace:
       at System.Data.Entity.Internal.LazyInternalConnection..ctor(DbContext context, String nameOrConnectionString)
       at System.Data.Entity.DbContext..ctor()
       at MvcTemplate.Data.Core.Context..ctor()
       at DynamicMethod(Object[] )
       at LightInject.ServiceContainer.TryGetInstance(Type serviceType) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:line 2597
       at LightInject.Mvc.LightInjectMvcDependencyResolver.GetService(Type serviceType) in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject.Mvc\LightInject.Mvc.cs:line 143
       at System.Web.Mvc.DependencyResolverExtensions.GetService[TService](IDependencyResolver resolver)
       at MvcTemplate.Components.Security.AuthorizationProvider.Refresh() in .\MVC5.Template_origin\MVC5.Template\src\MvcTemplate\Components\Security\Authorization\AuthorizationProvider.cs:line 51
       at MvcTemplate.Web.MvcApplication.RegisterAuthorization() in .\MVC5.Template_origin\MVC5.Template\src\MvcTemplate.Web\Global.asax.cs:line 96
       at MvcTemplate.Web.MvcApplication.Application_Start() in .\MVC5.Template_origin\MVC5.Template\src\MvcTemplate.Web\Global.asax.cs:line 29
  InnerException: System.Configuration.ConfigurationErrorsException
       HResult=-2146232062
       Message=The entry 'Context' has already been added. (.\MVC5.Template_origin\MVC5.Template\src\MvcTemplate.Web\web.config line 7)
       Source=System.Configuration
       BareMessage=The entry 'Context' has already been added.
       Filename=.\MVC5.Template_origin\MVC5.Template\src\MvcTemplate.Web\web.config
       Line=7
       StackTrace:
            at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
            at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
            at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
            at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
            at System.Web.HttpContext.GetSection(String sectionName)
            at System.Web.Configuration.HttpConfigurationSystem.GetSection(String sectionName)
            at System.Web.Configuration.HttpConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String configKey)
            at System.Configuration.ConfigurationManager.get_ConnectionStrings()
            at System.Data.Entity.Internal.AppConfig..ctor()
            at System.Data.Entity.Internal.AppConfig..cctor()
       InnerException: 
```

**Comment by Muchiachio** [comment]
You need to set `Web` as start up project before running the migrations on `Data` project, because running `upgrade-database` uses current `startup project` as it's configuration source.

**Comment by bs135** [comment]
Thank you for quick response.

I try to delete all and re-clone the sourcecode from github.
Then try as your guide.
But the problem is still the same.

Let me know if you need more information.

**Comment by Muchiachio** [comment]
Try adding `<clear />` before any of connections in your connection strings
```
<connectionStrings>
    <clear />
    <add name="Context" ... />
    <add name="TestingContext" ... />
</connectionStrings>
```

**Comment by bs135** [comment]
Thank you so much. It works!

Except `<clear />`, I must to add some `<remove ...>` element in web.config:

```xml
            <customHeaders>
                <remove name="X-Powered-By" />

                <remove name="X-Frame-Options" />
                <remove name="X-XSS-Protection" />
                <remove name="X-Content-Type-Options" />
                <remove name="Content-Security-Policy" />

                <add name="X-Frame-Options" value="deny" />
                <add name="X-XSS-Protection" value="1; mode=block" />
                <add name="X-Content-Type-Options" value="nosniff " />
                <add name="Content-Security-Policy" value="script-src 'self'; style-src 'self' 'unsafe-inline'" />
            </customHeaders>
```

I am very grateful for your help. 
It would be nice if you could explain a little more about `<clear />` in this case.

**Comment by Muchiachio** [comment]
These configuration entries are inherited through machine, iis, application and other configurations. Sometimes global configuration already has the same key as the one you want to add and you know that you don't have any other contexts, so you can just clear all inherited information and add your.

I will try looking at `customHeaders` values in different IIS version, because they may have been added in the newer versions by default, that's why you needed to readd them.

**Comment by bs135** [comment]
Thank you so much.
